### ISSUE TITLE
Filter silenced alert

### ISSUE THREAD

**Issue by arogarth** [ricoberger/Alertmanager#1]
Filter silenced alerts from api

using parameter `?silenced=false` to filter out silenced alerts

**Comment by ricoberger** [comment]
Hi @arogarth, it is now possible to specify the fields `silenced` and `inhibited` in the configuration to show/hide silenced and inhibited alerts.

This feature is available in version [1.4.0](https://github.com/ricoberger/Alertmanager/releases/tag/1.4.0)
